#!/bin/bash
NUMERO_CLIENTES=100000
perf stat -e instructions:u mpirun -n 4 -hostfile tg_host_1 ./tr -c $NUMERO_CLIENTES &> resultados_tr/T_${NUMERO_CLIENTES}_clientes_4_processadores
perf stat -e instructions:u mpirun -n 8 -hostfile tg_host_2 ./tr -c $NUMERO_CLIENTES &> resultados_tr/T_${NUMERO_CLIENTES}_clientes_8_processadores
perf stat -e instructions:u mpirun -n 12 -hostfile tg_host_3 ./tr -c $NUMERO_CLIENTES &> resultados_tr/T_${NUMERO_CLIENTES}_clientes_12_processadores
perf stat -e instructions:u mpirun -n 16 -hostfile tg_host_4 ./tr -c $NUMERO_CLIENTES &> resultados_tr/T_${NUMERO_CLIENTES}_clientes_16_processadores



